Development
suretrust/weather-app pull request #2
Opened 2019-09-04 15:09 UTC by suretrust

Kindly review.

2019-09-05 19:08 UTC, BalintMendli requested changes
Hi @suretrust ,

Wonderful work on the project. 👏 Nice UI, fetching and displaying data works as it should. Unit conversion works as well.

We just need to make some minor tweaks to make this perfect.

Please see my code comments below and make the requested changes. When it's done submit another Code Review Request.

If you happen to have any questions or concerns do not hesitate to contact me on Slack or here in the comments.

2019-09-05 19:08 UTC, BalintMendli commented on src/apiData.js
> +                weatherDetails.innerHTML = `<div class="animated rotateIn card  bg-secondary text-white my-3 mx-md-5 shadow-lg">
This module is doing too much. DOM related logic should be in a separate module. Please move it to a separate module file.

2019-09-05 19:08 UTC, BalintMendli commented on src/apiData.js
> +        .catch(error => error);
Error handling should happen here in the `catch` block. There could be errors when you don't get a response back and you don't handle those now.

2019-09-05 19:08 UTC, BalintMendli commented on src/conversion.js
> +})();
Why do we need an IIFE here? It is already a module. We could have just this: 
```
const fahrenheitToCelsius = (temp) => {
  return ((temp - 32) * (5 / 9)).toFixed(1);
}

const celsiusToFahrenheit = (temp) => {
  return ((temp * (9 / 5)) + 32).toFixed(1);
}

export { celsiusToFahrenheit, fahrenheitToCelsius }
```

2019-09-05 19:08 UTC, BalintMendli commented on src/clickListeners.js
> +            apiData(`http://api.openweathermap.org/data/2.5/weather?q=${getInputCity()}&units=imperial&APPID=e43078cb1a48713be6d68ea7035e03f0`);
Use the secure `https` link here otherwise it won't work on the deployed version.

2019-09-08 20:46 UTC, suretrust commented
All changes made as suggested. Kindly review.

2019-09-09 09:10 UTC, BalintMendli approved these changes
Hi @suretrust ,

All good now, this is a

## 👍 


You are a Promise wizard now 😉 

You can go ahead and merge the project.

_P.S. Please use [Git flow](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/)  for your next projects._

2019-09-09 09:10 UTC, zenott commented on src/apiData.js
> +                response.main
Consider using destructuring here for the response object.

2019-09-09 11:31 UTC, merged